(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";function escape(e){return e.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}function hide(e){for(var t=document.querySelectorAll(e),n=0;n<t.length;n++)t[n].style.display="none"}function show(e){for(var t=document.querySelectorAll(e),n=0;n<t.length;n++)t[n].style.display=null}function update(){keys=[],regexp=pathRegexp(_("#inputRoute").value,keys),_("#regexp-display").textContent=regexp.toString(),_("#keys-display").innerHTML=keys.length?"<ol>"+keys.map(function(e){return"<li>"+escape(e.name)+(e.optional?" (optional)":"")+"</li>"}).join("")+"</ol>":"There are no keys captured by this route",updatePath()}function updatePath(){var e=_("#inputPath").value;if(regexp.test(e)){hide(".is-not-match"),show(".is-match");var t=regexp.exec(e);_("#keys-results-display").innerHTML='<dl class="dl-horizontal">'+keys.map(function(e,n){return"<dt>"+escape(e.name)+"</dt><dd>"+escape(t[n+1])+"</dd>"}).join("")+"</dl>"}else show(".is-not-match"),hide(".is-match")}var pathRegexp=require("path-to-regexp"),debounce=require("debounce"),_=document.querySelector.bind(document);_("#inputRoute").addEventListener("input",debounce(update,100),!1),_("#inputPath").addEventListener("input",debounce(updatePath,100),!1);var keys,regexp;update();
},{"debounce":2,"path-to-regexp":4}],2:[function(require,module,exports){
var now=require("date-now");module.exports=function(n,u,t){function e(){var p=now()-a;u>p&&p>0?r=setTimeout(e,u-p):(r=null,t||(i=n.apply(o,l),r||(o=l=null)))}var r,l,o,a,i;return null==u&&(u=100),function(){o=this,l=arguments,a=now();var p=t&&!r;return r||(r=setTimeout(e,u)),p&&(i=n.apply(o,l),o=l=null),i}};
},{"date-now":3}],3:[function(require,module,exports){
function now(){return(new Date).getTime()}module.exports=Date.now||now;
},{}],4:[function(require,module,exports){
function escapeGroup(e){return e.replace(/([=!:$\/()])/g,"\\$1")}function pathtoRegexp(e,r,t){r&&!Array.isArray(r)&&(t=r,r=null),r=r||[],t=t||{};var n=t.strict,a=t.end!==!1,p=t.sensitive?"":"i",i=0;if(e instanceof RegExp){var u=e.source.match(/\((?!\?)/g)||[];return r.push.apply(r,u.map(function(e,r){return{name:r,delimiter:null,optional:!1,repeat:!1}})),attachKeys(e,r)}if(Array.isArray(e))return e=e.map(function(e){return pathtoRegexp(e,r,t).source}),attachKeys(new RegExp("(?:"+e.join("|")+")",p),r);e=e.replace(PATH_REGEXP,function(e,t,n,a,p,u,o,c){if(t)return t;if(c)return"\\"+c;var s="+"===o||"*"===o,l="?"===o||"*"===o;return r.push({name:a||i++,delimiter:n||"/",optional:l,repeat:s}),n=n?"\\"+n:"",p=escapeGroup(p||u||"[^"+(n||"\\/")+"]+?"),s&&(p=p+"(?:"+n+p+")*"),l?"(?:"+n+"("+p+"))?":n+"("+p+")"});var o="/"===e[e.length-1];return n||(e=(o?e.slice(0,-2):e)+"(?:\\/(?=$))?"),a||(e+=n&&o?"":"(?=\\/|$)"),attachKeys(new RegExp("^"+e+(a?"$":""),p),r)}module.exports=pathtoRegexp;var PATH_REGEXP=new RegExp(["(\\\\.)","([\\/.])?(?:\\:(\\w+)(?:\\(((?:\\\\.|[^)])*)\\))?|\\(((?:\\\\.|[^)])*)\\))([+*?])?","([.+*?=^!:${}()[\\]|\\/])"].join("|"),"g"),attachKeys=function(e,r){return e.keys=r,e};
},{}]},{},[1])


//# sourceMappingURL=build.js.map